const names1 = [
  'NullPointerPrince',
  '404NotFoundYou',
  'StackOverflowed',
  'CtrlAltElite',
  'CommitCrimes',
  'RubberDuckieDev',
  'PingMePlz',
  'BrbCompiling',
  'FatalSyntax',
  'BuggedButHappy',
  'InfiniteLoopHole',
  'SegFaultyLogic',
  'ByteMeMaybe',
  'SpaghettiCoder',
  'FullSnackDev',
  'KernelSandwich',
  'BoolinDev',
  'NaNStopper',
  'DevNullius',
  'TabbyTheDebugger',
  'LootBoxLad',
  'NoScopeCSharp',
  'Lagzilla',
  'RespawnResume',
  'CacheMeOutside',
];
const names2 = [
  'AimBotany',
  'CrashTestCutie',
  'YeetCompiler',
  'PixelPuncher',
  'AFKChef',
  'TeaBagger3000',
  'CaffeineLoop',
  'RAMenNoodles',
  '404SnaccNotFound',
  'HelloWorldDomination',
  'JavaTheHutt',
  'WiFried',
  'DebuggerDuck',
  'ExceptionHunter',
  'TheRealSlimShader',
  'SyntaxTerror',
  'ClickyMcClickface',
  'BananaForScale',
  'Devzilla',
  'MrRobotoCallsHome',
  'SudoNym',
  'OopsIDidItAgain',
  'MemeDrivenDev',
  'TypoNinja',
  'BitFlipper',
];

export function getRandomPlayerNames(): string[] {
  const randomIndex1 = Math.floor(Math.random() * names1.length);
  const randomIndex2 = Math.floor(Math.random() * names1.length);
  return [names1[randomIndex1], names2[randomIndex2]];
}
