name: Backend Unit-Tests

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Clear npm cache
      run: npm cache clean --force

    - name: Install Backend Dependencies
      run: npm ci
      working-directory: ./project/backend

    - name: Start Backend
      run: npx prisma migrate dev  --schema=database/prisma/schema.prisma fix-game-relations && npx prisma generate --schema=database/prisma/schema.prisma fix-game-relations && node.js  &
      working-directory: ./project/backend

    - name: Wait for server to be ready
      run: npx wait-on https://localhost:3000 --insecure
      timeout-minutes: 1

    - name: Run Jest Unit Tests
      run: npm test --trace on
      working-directory: ./project/backend/tests
